import { itemVisuals } from "./itemVisuals";

export type Language = "en" | "ar";
export type Localized = { en: string; ar: string };
export type CatalogItem = { name: Localized; detail: Localized; price: Localized; image: string };
const priced = (en: string, ar: string, usd: number, detailEn = "Reference starting price"): CatalogItem => ({
  name: { en, ar }, detail: { en: detailEn, ar: "سعر ابتدائي مرجعي" }, price: { en: `$${usd}`, ar: `${usd}$` }, image: itemVisuals[en],
});
const quoted = (en: string, ar: string, detailEn = "Scope, materials and final price confirmed after assessment"): CatalogItem => ({
  name: { en, ar }, detail: { en: detailEn, ar: "يحدد نطاق العمل والمواد والسعر النهائي بعد المعاينة" }, price: { en: "Quote on request", ar: "السعر عند الطلب" }, image: itemVisuals[en],
});

export const serviceCatalog: Record<string, CatalogItem[]> = {
  Electrical: [
    priced("Electrical inspection visit", "معاينة كهربائية", 20, "Inspection visit"),
    priced("Install spotlight", "تركيب سبوت لايت", 2, "Per unit"),
    priced("Install incandescent bulb", "تركيب لمبة", 2, "Per unit"),
    priced("Install tube light", "تركيب إضاءة أنبوبية", 2, "Per unit"),
    priced("Install chandelier bulb", "تركيب لمبة ثريا", 2, "Per unit"),
    priced("Switch / socket replacement", "استبدال مفتاح أو مقبس", 8),
    priced("Switch / socket installation", "تركيب مفتاح أو مقبس", 10),
    priced("AC / heater switch plate", "تركيب لوحة مفتاح للمكيف أو السخان", 11),
    priced("Wall ventilation fan", "تركيب مروحة تهوية جدارية", 15),
    priced("Ceiling ventilation fan", "تركيب مروحة تهوية سقفية", 18),
    priced("TV installation / mounting", "تركيب أو تثبيت تلفاز", 18),
    priced("Electric water heater", "تركيب سخان مياه كهربائي", 25),
    priced("Chandelier installation", "تركيب ثريا", 22),
  ],
  Plumbing: [
    priced("Book a visit", "حجز معاينة", 20, "Inspection visit"),
    priced("Wash basin blockage removal", "فتح انسداد مغسلة", 27),
    priced("Toilet blockage removal", "فتح انسداد مرحاض", 30),
    priced("Drain blockage removal", "فتح انسداد مصرف", 30),
    priced("Flush tank installation / repair", "تركيب أو إصلاح خزان الطرد", 30),
    priced("Toilet seat cover replacement", "استبدال غطاء المرحاض", 15),
    priced("Toilet installation / repair", "تركيب أو إصلاح مرحاض", 50),
    priced("Mixer tap installation", "تركيب خلاط مياه", 27),
    priced("Normal tap installation", "تركيب حنفية عادية", 24),
    priced("Tap leakage repair", "إصلاح تسريب حنفية", 15),
    priced("Wash basin leakage repair", "إصلاح تسريب مغسلة", 20),
    priced("Shower leakage repair", "إصلاح تسريب دش", 20),
    priced("Geyser / washing machine leak", "إصلاح تسريب سخان أو غسالة", 25),
    priced("Geyser installation / removal", "تركيب أو فك سخان", 40),
    priced("Jet spray / bidet installation", "تركيب شطاف", 15),
    priced("Wash basin installation / removal", "تركيب أو فك مغسلة", 40),
    priced("Shower head installation", "تركيب رأس دش", 27),
    priced("Water valve installation / repair", "تركيب أو إصلاح صمام مياه", 15),
  ],
  "Complete fixings & repairs": [
    priced("Handyman by the hour", "حجز عامل صيانة بالساعة", 24, "Starting handyman rate"),
    priced("Mirror installation", "تركيب مرآة", 18),
    priced("Shelf installation", "تركيب رف", 15),
    priced("Bathroom accessory", "تركيب إكسسوار حمام", 15),
    priced("Painting (small item)", "دهان قطعة صغيرة", 15),
    priced("Wall / door clothes hanger", "تركيب شماعة جدارية أو باب", 21),
    priced("Ceiling clothes hanger", "تركيب شماعة سقفية", 30),
    priced("Bed support repair", "إصلاح دعامة سرير", 21),
    priced("Bed legs / headboard repair", "إصلاح أرجل أو لوح سرير", 21),
    priced("Cupboard hinge installation", "تركيب مفصلات خزانة", 15),
    priced("Cupboard handle replacement", "استبدال مقبض خزانة", 12),
    priced("Cupboard lock installation", "تركيب قفل خزانة", 12),
    priced("Cupboard lock repair", "إصلاح قفل خزانة", 12),
    priced("Drawer channel replacement", "استبدال مجرى درج", 15),
    priced("Door accessory installation", "تركيب إكسسوار باب", 15),
    priced("Door hinge installation", "تركيب مفصلات باب", 15),
    priced("Door lock installation", "تركيب قفل باب", 24),
    priced("Door lock repair", "إصلاح قفل باب", 27),
    priced("Door closer installation", "تركيب غالق باب", 21),
    priced("Wooden door installation", "تركيب باب خشبي", 40),
    priced("Minor wooden door repair", "إصلاح بسيط لباب خشبي", 21),
    priced("Major wooden door repair", "إصلاح كبير لباب خشبي", 30),
    priced("Door peephole installation", "تركيب عين سحرية", 18),
    priced("Curtain rod installation", "تركيب قضيب ستارة", 21),
    priced("Motorized curtain installation", "تركيب ستارة كهربائية", 49),
    priced("Non-motorized curtain installation", "تركيب ستارة عادية", 30),
  ],
  "Carpentry & furniture repairs": [
    priced("Single bed assembly", "تركيب سرير مفرد", 21),
    priced("Double bed assembly", "تركيب سرير مزدوج", 33),
    priced("Hydraulic bed assembly", "تركيب سرير هيدروليك", 46),
    priced("Loft / bunk bed assembly", "تركيب سرير مرتفع أو بطابقين", 37),
    priced("Normal door wardrobe assembly", "تركيب خزانة بأبواب عادية", 18),
    priced("Sliding door wardrobe assembly", "تركيب خزانة بأبواب جرّ", 36),
    priced("Dining table assembly", "تركيب طاولة طعام", 21),
    priced("Dining chair assembly", "تركيب كرسي طعام", 5, "Per chair"),
    priced("Dining table with chairs", "تركيب طاولة مع كراسي", 28),
    priced("Side table assembly", "تركيب طاولة جانبية", 6),
    priced("Gaming chair assembly", "تركيب كرسي ألعاب", 15),
    priced("Study table assembly", "تركيب طاولة دراسة", 21),
    priced("Office chair assembly", "تركيب كرسي مكتب", 6),
    priced("Standing table assembly", "تركيب طاولة مرتفعة", 37),
    priced("Coffee table assembly", "تركيب طاولة قهوة", 9),
    priced("Table / chair wheel fitting", "تركيب عجلات طاولة أو كرسي", 6),
    priced("Changing table assembly", "تركيب طاولة تغيير", 9),
    priced("High chair assembly", "تركيب كرسي أطفال مرتفع", 9),
    priced("Cot assembly", "تركيب سرير رضيع", 14),
    priced("Children's bed assembly", "تركيب سرير أطفال", 21),
    priced("Sofa assembly", "تركيب أريكة", 28),
    priced("Sofa bed assembly", "تركيب أريكة سرير", 37),
    priced("Corner sofa assembly", "تركيب أريكة زاوية", 37),
    priced("Recliner assembly", "تركيب كرسي استرخاء", 12),
    priced("TV bench assembly", "تركيب طاولة تلفاز", 28),
    priced("TV unit assembly", "تركيب وحدة تلفاز", 64),
    priced("Swing chair assembly", "تركيب كرسي أرجوحة", 21),
    priced("Patio dining set assembly", "تركيب طقم طعام خارجي", 37),
  ],
  "Home appliances": [
    priced("AC deep cleaning — split", "تنظيف عميق لمكيف سبليت", 30),
    priced("AC deep cleaning — window", "تنظيف عميق لمكيف شباك", 27),
    priced("AC repair", "إصلاح مكيف", 27),
    priced("Freon refill", "تعبئة فريون", 92),
    priced("Freon refill + deep cleaning", "تعبئة فريون مع تنظيف عميق", 110),
    priced("AC relocation", "نقل مكيف", 92),
    priced("AC installation", "تركيب مكيف", 49),
    priced("AC uninstallation", "فك مكيف", 33),
  ],
  Waterproofing: [
    quoted("Roof waterproofing", "عزل الأسطح", "Area and condition assessed before quotation"),
    quoted("Balcony waterproofing", "عزل الشرفات", "Area and condition assessed before quotation"),
    quoted("Wet-area waterproofing", "عزل المناطق الرطبة", "Area and condition assessed before quotation"),
  ],
  "Aluminium & glass": [
    quoted("Window and door repair", "إصلاح نوافذ وأبواب", "Quotation depends on measurements and materials"),
    quoted("Glass partition", "فاصل زجاجي", "Quotation depends on measurements and glass type"),
    quoted("Sliding system repair", "إصلاح نظام جرّ", "Quotation depends on measurements and hardware"),
  ],
  "Steel & Style": [
    quoted("Steel railing", "درابزين حديد", "Custom design and site measurement"),
    quoted("Steel gate repair", "إصلاح بوابة حديد", "Condition and materials assessed before quotation"),
    quoted("Custom steel detail", "تفصيل حديد حسب الطلب", "Custom design and site measurement"),
  ],
  "Finishes & civil works": [
    quoted("Painting", "دهان", "Area, preparation and finish assessed before quotation"),
    quoted("Tiling", "تبليط", "Area, substrate and materials assessed before quotation"),
    quoted("Flooring", "أرضيات", "Area, material and preparation assessed before quotation"),
    quoted("Walls and ceilings", "جدران وأسقف", "Condition and finish assessed before quotation"),
  ],
  "Special request": [
    quoted("Property consultancy", "استشارة عقارية", "Scope defined after the first conversation"),
    quoted("Creative design", "تصميم إبداعي", "Scope defined after the first conversation"),
    quoted("Remodelling", "تجديد وإعادة تصميم", "Scope, materials and schedule assessed before quotation"),
  ],
};



export const serviceItems = [
  { en: "Electrical", ar: "أعمال الكهرباء", text: { en: "Installation, wiring, lighting and dependable electrical repairs.", ar: "تركيب وتمديدات وإنارة وإصلاحات كهربائية موثوقة." }, price: { en: "From $12", ar: "ابتداءً من 12$" }, image: "./assets/onefix-electrical.jpg" },
  { en: "Plumbing", ar: "أعمال السباكة", text: { en: "Leak repairs, pipe installation, water heaters and drainage support.", ar: "إصلاح التسريبات وتركيب الأنابيب وسخانات المياه وتصريفها." }, price: { en: "From $24", ar: "ابتداءً من 24$" }, image: "./assets/onefix-plumbing.jpg" },
  { en: "Complete fixings & repairs", ar: "إصلاحات متكاملة", text: { en: "Doors, locks, cabinets, kitchens, wardrobes and everyday fixes.", ar: "أبواب وأقفال وخزائن ومطابخ ودواليب وإصلاحات يومية." }, price: { en: "From $24", ar: "ابتداءً من 24$" }, image: "./assets/onefix-complete-repairs.jpg" },
  { en: "Carpentry & furniture repairs", ar: "النجارة وإصلاح الأثاث", text: { en: "Custom shelving, joinery, furniture fixing and practical woodwork.", ar: "رفوف وأعمال نجارة وإصلاح أثاث وحلول خشبية عملية." }, price: { en: "From $21", ar: "ابتداءً من 21$" }, image: "./assets/onefix-carpentry.jpg" },
  { en: "Home appliances", ar: "الأجهزة المنزلية", text: { en: "Careful help with everyday appliance issues and coordination.", ar: "مساعدة دقيقة في أعطال الأجهزة المنزلية والتنسيق اللازم." }, price: { en: "From $25", ar: "ابتداءً من 25$" }, image: "./assets/onefix-appliance-repair.jpg" },
  { en: "Waterproofing", ar: "العزل المائي", text: { en: "Protect roofs, balconies, walls and wet areas from water damage.", ar: "حماية الأسطح والشرفات والجدران والمناطق الرطبة من أضرار المياه." }, price: { en: "Quote on request", ar: "السعر عند الطلب" }, image: "./assets/onefix-waterproofing.jpg" },
  { en: "Aluminium & glass", ar: "الألمنيوم والزجاج", text: { en: "Windows, doors, partitions, glass panels and practical fittings.", ar: "نوافذ وأبواب وفواصل وزجاج وتركيبات عملية." }, price: { en: "Quote on request", ar: "السعر عند الطلب" }, image: "./assets/onefix-aluminium-glass.jpg" },
  { en: "Steel & Style", ar: "الحديد والستايل", text: { en: "Made-to-fit steel details, repair work and clean finishing.", ar: "تفاصيل حديدية حسب الطلب وإصلاحات وتشطيبات أنيقة." }, price: { en: "Quote on request", ar: "السعر عند الطلب" }, image: "./assets/onefix-steel-style.jpg" },
  { en: "Finishes & civil works", ar: "التشطيبات والأعمال المدنية", text: { en: "Painting, tiling, flooring, walls, ceilings and finishing details.", ar: "دهان وبلاط وأرضيات وجدران وأسقف وتفاصيل تشطيب." }, price: { en: "Quote on request", ar: "السعر عند الطلب" }, image: "./assets/onefix-finishes-civil.jpg" },
  { en: "Special request", ar: "طلب خاص", text: { en: "Consultancy, creative design and remodelling for a more considered result.", ar: "استشارات وتصميم إبداعي وتجديد لمساحة مدروسة ومتكاملة." }, price: { en: "Quote on request", ar: "السعر عند الطلب" }, image: "./assets/onefix-special-request.jpg", special: true },
];

