export const itemVisuals: Record<string, string> = {
  "Electrical inspection visit": "./assets/onefix-item-electrical-inspection.jpg",
  "Install spotlight": "./assets/onefix-item-electrical-spotlight.jpg",
  "Install incandescent bulb": "./assets/onefix-item-electrical-bulb.jpg",
  "Install tube light": "./assets/onefix-item-electrical-tube-light.jpg",
  "Install chandelier bulb": "./assets/onefix-item-electrical-chandelier-bulb.jpg",
  "Switch / socket replacement": "./assets/onefix-item-electrical-switch-replacement.jpg",
  "Switch / socket installation": "./assets/onefix-item-electrical-switch-installation.jpg",
  "AC / heater switch plate": "./assets/onefix-item-electrical-ac-heater-switch.jpg",
  "Wall ventilation fan": "./assets/onefix-item-electrical-wall-fan.jpg",
  "Ceiling ventilation fan": "./assets/onefix-item-electrical-ceiling-fan.jpg",
  "TV installation / mounting": "./assets/onefix-item-electrical-tv-mounting.jpg",
  "Electric water heater": "./assets/onefix-item-electrical-water-heater.jpg",
  "Chandelier installation": "./assets/onefix-item-electrical-chandelier-installation.jpg",

  "Book a visit": "./assets/onefix-item-plumbing-book-by-hour.jpg",
  "Wash basin blockage removal": "./assets/onefix-item-plumbing-wash-basin-blockage-retry.jpg",
  "Toilet blockage removal": "./assets/onefix-item-plumbing-toilet-blockage-retry.jpg",
  "Drain blockage removal": "./assets/onefix-item-plumbing-drain-blockage-retry.jpg",
  "Flush tank installation / repair": "./assets/onefix-item-plumbing-flush-tank-retry.jpg",
  "Toilet seat cover replacement": "./assets/onefix-item-plumbing-toilet-seat-retry.jpg",
  "Toilet installation / repair": "./assets/onefix-item-plumbing-toilet-installation.jpg",
  "Mixer tap installation": "./assets/onefix-item-plumbing-mixer-tap.jpg",
  "Normal tap installation": "./assets/onefix-item-plumbing-normal-tap.jpg",
  "Tap leakage repair": "./assets/onefix-item-plumbing-tap-leak.jpg",
  "Wash basin leakage repair": "./assets/onefix-item-plumbing-wash-basin-leak.jpg",
  "Shower leakage repair": "./assets/onefix-item-plumbing-shower-leak.jpg",
  "Geyser / washing machine leak": "./assets/onefix-item-plumbing-geyser-washing-machine-leak.jpg",
  "Geyser installation / removal": "./assets/onefix-item-plumbing-geyser-installation.jpg",
  "Jet spray / bidet installation": "./assets/onefix-item-plumbing-jet-spray-bidet.jpg",
  "Wash basin installation / removal": "./assets/onefix-item-plumbing-wash-basin-installation.jpg",
  "Shower head installation": "./assets/onefix-item-plumbing-shower-head.jpg",
  "Water valve installation / repair": "./assets/onefix-item-plumbing-water-valve.jpg",

  "Handyman by the hour": "./assets/onefix-item-fixings-hourly-handyman.jpg",
  "Mirror installation": "./assets/onefix-item-fixings-mirror.jpg",
  "Shelf installation": "./assets/onefix-item-fixings-shelf.jpg",
  "Bathroom accessory": "./assets/onefix-item-fixings-bathroom-accessory-retry.jpg",
  "Painting (small item)": "./assets/onefix-item-fixings-small-painting-retry.jpg",
  "Wall / door clothes hanger": "./assets/onefix-item-fixings-wall-hanger-retry.jpg",
  "Ceiling clothes hanger": "./assets/onefix-item-fixings-ceiling-hanger-retry.jpg",
  "Bed support repair": "./assets/onefix-item-fixings-bed-support-retry.jpg",
  "Bed legs / headboard repair": "./assets/onefix-item-fixings-bed-legs-headboard.jpg",
  "Cupboard hinge installation": "./assets/onefix-item-fixings-cupboard-hinge.jpg",
  "Cupboard handle replacement": "./assets/onefix-item-fixings-cupboard-handle.jpg",
  "Cupboard lock installation": "./assets/onefix-item-fixings-cupboard-lock-installation-retry.jpg",
  "Cupboard lock repair": "./assets/onefix-item-fixings-cupboard-lock-repair-retry.jpg",
  "Drawer channel replacement": "./assets/onefix-item-fixings-drawer-channel-retry.jpg",
  "Door accessory installation": "./assets/onefix-item-fixings-door-accessory.jpg",
  "Door hinge installation": "./assets/onefix-item-fixings-door-hinge-retry.jpg",
  "Door lock installation": "./assets/onefix-item-door-lock-installation-final.jpg",
  "Door lock repair": "./assets/onefix-item-fixings-door-lock-repair-retry.jpg",
  "Door closer installation": "./assets/onefix-item-fixings-door-closer.jpg",
  "Wooden door installation": "./assets/onefix-item-fixings-wooden-door-installation.jpg",
  "Minor wooden door repair": "./assets/onefix-item-fixings-minor-door-repair.jpg",
  "Major wooden door repair": "./assets/onefix-item-fixings-major-door-repair-retry.jpg",
  "Door peephole installation": "./assets/onefix-item-fixings-door-peephole-retry.jpg",
  "Curtain rod installation": "./assets/onefix-item-curtain-rod-installation-final.jpg",
  "Motorized curtain installation": "./assets/onefix-item-fixings-motorized-curtain.jpg",
  "Non-motorized curtain installation": "./assets/onefix-item-manual-curtain-final.jpg",

  "Single bed assembly": "./assets/onefix-item-furniture-single-bed.jpg",
  "Double bed assembly": "./assets/onefix-item-furniture-double-bed-retry.jpg",
  "Hydraulic bed assembly": "./assets/onefix-item-furniture-hydraulic-bed-retry.jpg",
  "Loft / bunk bed assembly": "./assets/onefix-item-furniture-bunk-bed.jpg",
  "Normal door wardrobe assembly": "./assets/onefix-item-furniture-normal-wardrobe.jpg",
  "Sliding door wardrobe assembly": "./assets/onefix-item-sliding-wardrobe-final.jpg",
  "Dining table assembly": "./assets/onefix-item-furniture-dining-table.jpg",
  "Dining chair assembly": "./assets/onefix-item-furniture-dining-chair-retry.jpg",
  "Dining table with chairs": "./assets/onefix-item-dining-set-final.jpg",
  "Side table assembly": "./assets/onefix-item-furniture-side-table-retry.jpg",
  "Gaming chair assembly": "./assets/onefix-item-furniture-gaming-chair.jpg",
  "Study table assembly": "./assets/onefix-item-furniture-study-table.jpg",
  "Office chair assembly": "./assets/onefix-item-office-chair-final.jpg",
  "Standing table assembly": "./assets/onefix-item-furniture-standing-table-retry.jpg",
  "Coffee table assembly": "./assets/onefix-item-coffee-table-final.jpg",
  "Table / chair wheel fitting": "./assets/onefix-item-wheel-fitting-final.jpg",
  "Changing table assembly": "./assets/onefix-item-furniture-changing-table-retry.jpg",
  "High chair assembly": "./assets/onefix-item-furniture-high-chair.jpg",
  "Cot assembly": "./assets/onefix-item-furniture-cot.jpg",
  "Children's bed assembly": "./assets/onefix-item-childrens-bed-final.jpg",
  "Sofa assembly": "./assets/onefix-item-furniture-sofa-retry.jpg",
  "Sofa bed assembly": "./assets/onefix-item-sofa-bed-final.jpg",
  "Corner sofa assembly": "./assets/onefix-item-furniture-corner-sofa.jpg",
  "Recliner assembly": "./assets/onefix-item-furniture-recliner.jpg",
  "TV bench assembly": "./assets/onefix-item-tv-bench-final.jpg",
  "TV unit assembly": "./assets/onefix-item-furniture-tv-unit.jpg",
  "Swing chair assembly": "./assets/onefix-item-furniture-swing-chair-retry.jpg",
  "Patio dining set assembly": "./assets/onefix-item-furniture-patio-dining.jpg",

  "AC deep cleaning — split": "./assets/onefix-item-appliance-ac-split-cleaning-retry.jpg",
  "AC deep cleaning — window": "./assets/onefix-item-appliance-ac-window-cleaning.jpg",
  "AC repair": "./assets/onefix-item-appliance-ac-repair-retry.jpg",
  "Freon refill": "./assets/onefix-item-freon-refill-stock.jpg",
  "Freon refill + deep cleaning": "./assets/onefix-item-appliance-freon-cleaning-package.jpg",
  "AC relocation": "./assets/onefix-item-ac-relocation-stock.jpg",
  "AC installation": "./assets/onefix-item-appliance-ac-installation.jpg",
  "AC uninstallation": "./assets/onefix-item-appliance-ac-uninstallation.jpg",

  "Roof waterproofing": "./assets/onefix-item-waterproofing-roof-retry.jpg",
  "Balcony waterproofing": "./assets/onefix-item-balcony-waterproofing-final.jpg",
  "Wet-area waterproofing": "./assets/onefix-item-waterproofing-wet-area.jpg",
  "Window and door repair": "./assets/onefix-item-aluminium-window-door-repair.jpg",
  "Glass partition": "./assets/onefix-item-glass-partition-final.jpg",
  "Sliding system repair": "./assets/onefix-item-aluminium-sliding-system.jpg",
  "Steel railing": "./assets/onefix-item-steel-railing-final.jpg",
  "Steel gate repair": "./assets/onefix-item-steel-gate-repair.jpg",
  "Custom steel detail": "./assets/onefix-item-steel-frame-canopy-retry.jpg",
  Painting: "./assets/onefix-item-finishes-painting-retry.jpg",
  Tiling: "./assets/onefix-item-finishes-tiling-flooring.jpg",
  Flooring: "./assets/onefix-item-finishes-flooring.jpg",
  "Walls and ceilings": "./assets/onefix-item-finishes-wall-ceiling-repair.jpg",
  "Property consultancy": "./assets/onefix-item-special-design-consultancy.jpg",
  "Creative design": "./assets/onefix-item-special-creative-design.jpg",
  Remodelling: "./assets/onefix-item-special-remodelling.jpg",
};
